# Generated by Django 4.2.1 on 2023-05-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_question_answer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='creation_date',
            field=models.DateTimeField(),
        ),
    ]
